### ISSUE TITLE
[Question] How to filter stories by content-type?

### ISSUE THREAD

**Issue by ekkaiasmith** [storyblok/gridsome-source-storyblok#12]
[Question] Hi, I would like to filter stories according to their content-type but I don't find how to do in the documentation :/

**Comment by invatom** [comment]
As far as I can find, this is not possible. It is basically the same as my question, if it is possible to run queries against the content object. 

Without somehow specifying a schema and supplying that to the plugin it will not work.

If we look at the default schema

https://github.com/storyblok/gridsome-source-storyblok/blob/master/utils/create-schema.js

we see that content is just a JSONObject that is completely opaque until you have it in Gridsome and then you can run regular filtering in javascript on it.

**Comment by ekkaiasmith** [comment]
This works perfectly, thank you
