### ISSUE TITLE
[Question] How to load a story in a static query by its path?

### ISSUE THREAD

**Issue by tjbp** [storyblok/gridsome-source-storyblok#13]
I have several stories in a content folder named "Shared" - each contains data that is loaded by static queries in generic components, such as the navigation bar and footer. I want to load that data using a static query, but using the story's ID as an argument is not workable since this project needs to be compatible with more than one space.

```
<static-query>
query StoryblokEntry {
  storyblokEntry(path: "shared/navbar") {
    content
  }
}
</static-query>
```

Nothing is returned by the above query, though "path" is a valid argument.

I have also created a second config specifically for the Navbar story:

```
    {
      use: 'gridsome-source-storyblok',
      options: {
        client: {
          accessToken: process.env.GRIDSOME_STORYBLOK_API_KEY
        },
        params: {
          starts_with: 'shared/navbar'
        },
        version: 'draft',
        typeName: 'NavbarEntry'
      }
    },
```

With the above, the following still returns nothing:

```
<static-query>
query NavbarEntry {
  navbarEntry {
    content
  }
}
</static-query>
```

**Comment by onefriendaday** [comment]
To include a global item you could something like this:
https://github.com/storyblok/storyblok-gridsome-boilerplate-moon/blob/master/src/templates/StoryblokEntry.vue#L50

**Comment by tjbp** [comment]
> To include a global item you could something like this:
> https://github.com/storyblok/storyblok-gridsome-boilerplate-moon/blob/master/src/templates/StoryblokEntry.vue#L50

Thanks @onefriendaday that works well!
