### ISSUE TITLE
[Question] How to create pages to list stories by tag?

### ISSUE THREAD

**Issue by ekkaiasmith** [storyblok/gridsome-source-storyblok#14]
[Question] I would like to have pages for listing stories which have the same tags. Is it possible and how to do it?

The solution is probably to use `api.createPages` in `gridsome.server.js` but i'm a bit confused and i don't know how to use it well

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue!

[In the last version of our plugin - v1.0.0](https://github.com/storyblok/gridsome-source-storyblok/releases/tag/v1.0.0), we implemented by default, the relationship between tags and stories. You can check the [section of documentation](https://github.com/storyblok/gridsome-source-storyblok#working-with-tags) than explains that.
