### ISSUE TITLE
Adding additional query parameter (argument) uuid

### ISSUE THREAD

**Issue by moritzlaube** [storyblok/gridsome-source-storyblok#21]
Hi there! Would you be so kind and explain to me how I can add an additional query parameter to my graphql query? Specifically I do need the uuid (not the id) to fetch my stories. This is the only parameter the link object in Storyblok would give me.

This is what I am getting back from the Storyblok Delivery API:
```
"blog_select": [
"2d3c12d8-8f8b-4a40-97cd-xxxxxxxxxxx",
"ce5e8052-476b-4eb6-9d2b-xxxxxxxxxxx",
"2c12c204-1837-4913-b2ff-xxxxxxxxxx"
]
```

And I want to use those uuid's to fetch the respective Stories. So my static-query can then look like this: 

```
{
  storyblokEntry(uuid: 2d3c12d8-8f8b-4a40-97cd-xxxxxxxxxxx) {
    content
  }
}
```

Thanks for your help!

**Comment by moritzlaube** [comment]
Remark: 
I was playing with Storyblok's API Playground a bit. And basically I'd like to be able to perform a request like that to get the Story by uuid:

```
{
  allStoryblokEntry(by_uuids: "2c12c204-1837-4913-b2ff-64dead64f4a2") {
    items {
      content {
        _uid
        body
      }
    }
  }
}
```

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue!

According the [Gridsome documentation (Querying data)](https://gridsome.org/docs/querying-data/#querying-single-nodes), until the moment, it's only possible to get a single node by using the `id` property.

But, you can use the [filter statement](https://gridsome.org/docs/filtering-data/), filtering by `uuid`, like the following:

```graphql
{
  allStoryblokEntry (filter: { uuid: { eq: "YOUR_UUID" } }) {
    edges {
      node {
        id
        uuid
        name
        full_slug
      }
    }
  }
}
```
