### ISSUE TITLE
[Question] Noob question: How to eager load?

### ISSUE THREAD

**Issue by pmochine** [storyblok/gridsome-source-storyblok#5]
I opened up [this question in StackOverflow](https://stackoverflow.com/questions/58842454/how-to-load-nested-data-with-graphql-from-storyblok), but couldn't get an answer yet. Maybe I have here more luck.

My background is coming from normal REST-APIs and now I'm a bit overwhelmed.

I'm trying to fetch with one graphql query all needed information for a blog post.

The first query loads with the ID everything from a specific blog post but is not loading nested data like categories or authors.

For example:

    <page-query>
        query StoryblokEntry ($id: ID) {
            storyblokEntry (id: $id) {
                id
                slug
                content
            }
        }
    </page-query>

When I test the query with the ID of "story-3850216-default", I get this result:

    {
      "data": {
        "storyblokEntry": {
          "id": "story-3850216-default",
          "slug": "hello-world",
          "content": {
            "_uid": "f5a0bd9d-ec13-4381-ae5f-a7e2bb093fbe",
            "title": "Hello World 👋",
            "authors": [
              "61dec800-1b17-443e-961a-1cf8ef08d803"
            ],
            "content": "hi",
            "component": "article-post",
            "categories": [
              "e1509e6e-2007-4d4b-8857-4bc1105c5505"
            ],
          }
        }
      }
    }

What should I do, so that the values of authors and categories are eager loaded?

Edit:

Or better how could I implement this kinda of query?

```
{
  ArticlepostItems {
    items {
      id
      created_at
      content {
        component
        content
        title
        authors {
          content
        }
        categories {
          content
        }
      }
    }
  }
}

```

Or do I have a thinking error? Do I even need this plugin or is it just to create components dynamically, but is not for nested data?

**Comment by onefriendaday** [comment]
You need to add resolve_relations to the params config. 

```
{
  use: 'gridsome-source-storyblok',
  options: {
    ...
    params: {
      resolve_relations: 'article-post.authors,article-post.categories'
    }
  }
}
```

**Comment by pmochine** [comment]
@onefriendaday I need your help. I have updated from 0.2.2 to 1.0.2 but suddenly `resolve_relations` is not working anymore.

Could you please update this above example again?

**Comment by emanuelgsouza** [comment]
Hi @pmochine ! The `params` field was moved to `types.story` object. Check the following section [The options object in details](https://github.com/storyblok/gridsome-source-storyblok#the-options-object-in-details) for more details.
