### ISSUE TITLE
[Question] Is it possible to run queries on data inside the content JSONObject?

### ISSUE THREAD

**Issue by invatom** [storyblok/gridsome-source-storyblok#7]
We use this plugin with gridsome and storyblok and it works great.

However, when fetching articles, I would sometimes like to filter on some value inside the content field.
Currently I cannot figure out if this is even possible. Also just selecting a few fields inside the content field would be nice.

Is it possible to specify a schema for some types manually? or have them be autogenerated?

As there is no schema right now I get 
"message": "Field \"content\" must not have a selection since type \"JSONObject\" has no subfields.",
back in the playground.

Any ideas?

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue!

It's not possible select any fields from a JSONObject type, it's a general type for JSON objects.

It's not possible to create a schema. Check [here](https://github.com/storyblok/gridsome-source-storyblok/blob/master/utils/create-schema.js) to view how to our schema is created
