### ISSUE TITLE
downloadImage not working

### ISSUE THREAD

**Issue by pmcp** [storyblok/gridsome-source-storyblok#8]
Hi, I'm trying to use the downloadImage option, but I can't get it working.

```    {
      use: 'gridsome-source-storyblok',
      options: {
        client: {
          accessToken: ***
        },
        downloadImages: true,
        imageDirectory: 'storyblok_images',
        params: {
          resolve_links: 'story',
          resolve_relations: 'navigation, preview-articles.articles, page-map.organisations,partners.partners,partners.poweredby,existing_element.element'
        },
      }
    }
```

And in my components i have code like

`<g-image :src="image.filename" :alt="image.name" width="500"/>
`

Am i doing something wrong?

**Comment by emanuelgsouza** [comment]
Hi! Looking at `g-image` tag, I see that you use `image.filename`property, but, the correct is `image.path` because the `path` property contains the relative path for your image.

**Comment by pmcp** [comment]
Oh, ok, than i'm missing something how the retrieval of images works. I don't get a path property in the asset object: https://www.storyblok.com/docs/api/management#core-resources/assets/the-asset-object

**Comment by emanuelgsouza** [comment]
Ok. When do you use the our Gridsome plugin, it will be download images in your `src` path and put the location relative to them in GraphQL. So it's not the same as using the Management API.

**Comment by pmcp** [comment]
Ok, but can you explain then how i get them to download. If i run gridsome develop or gridsome build, there are now images getting downloaded. So I don't know what I'm doing wrong.

**Comment by emanuelgsouza** [comment]
For download the images, it's just use the `downloadImages` option in your config storyblok plugin like you already showed above. You can navigate into GraphQL editor for looking those images.

The images will be download in `develop` and `build` commands.

For now, if your images did not download in the `path` that you configured, I have a question for you: what are the your images urls? Because the code until the moment just download the Storyblok images ([Link to the code that process the image](https://github.com/storyblok/gridsome-source-storyblok/blob/master/utils/process-image.js))

**Comment by pmcp** [comment]
So, for example, in page "Home" I've got this field with image:

cover_image: "https://a.storyblok.com/f/69682/2560x1700/4186fb3a5a/1.jpg"

I set the downloadImages to true, like I posted above. In the console i get: "Processing story Home to search images and download them..." . The folder gets created (storyblok_images) but there are no images in there.

**Comment by emanuelgsouza** [comment]
Can you share your `gridsome.config.js` file?

**Comment by pmcp** [comment]
Copy pasted it in a gist: https://gist.github.com/pmcp/c0f7e1fec364b485d5759a0e001d155a

**Comment by emanuelgsouza** [comment]
@pmcp, we believe that [last version](https://github.com/storyblok/gridsome-source-storyblok/releases/tag/v0.2.1) of gridsome-source-storyblok package resolves your problem.
